"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Thorsten Ball"
email = "mrnugget@gmail.com"

[aliases]
# tug: bring nearest bookmark up to recent commit
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# retrunk:
# `jj rebase -d 'trunk()'` is shorthand for `jj rebase -b @ -d 'trunk()'`
#
# What that does:
#
# `-b @` rebases the entire branch that the current @ is on relative to the destination. (Default),
# `-d trunk()` sets the destination. trunk() finds the most recent `main | master | trunk` branch thats on a remote. trunk() is builtin.
retrunk = ["rebase", "-d", "trunk()"]

# retrunk:
# combine all of the revs from the current one to the start of the "branch" into one
collapse = ["squash", "-f", "branch_start(@)+::@", "-t", "branch_start(@)"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

# From indigo
"branch_start(to)" = "heads(::to & trunk())+ & ::to"

# From mitchellh
[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
diff-editor = ":builtin"
merge-editor = ":builtin"
